development:
    adapter: postgresql
    encoding: unicode
    database: sample_app_dev_db
    pool: 5
    username: georgiosperatinos
    password:

test:
    adapter: postgresql
    encoding: unicode
    database: sample_app_test_db
    pool: 5
    username: georgiosperatinos
    password:

host: localhost